version: '3'

services:
  postgres:
    image: docker.io/postgres:9.6
    restart: always
    volumes:
      - ./init/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./data/guacamole:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
    networks:
      - guac
  guacd:
    image: docker.io/guacamole/guacd:1.3.0
    restart: always
    networks:
      - guac
    ports:
      - "4822:4822"
  guacamole:
    image: docker.io/guacamole/guacamole:1.3.0
    restart: always
    ports:
      - "8080:8080"
    hostname: guacamole
    networks:
      guac:
    volumes:
      - ./openid/guacamole-auth-openid-1.3.0.jar:/opt/guacamole/openid/guacamole-auth-openid-1.3.0.jar
        #- ./init/guacamole.crt:/usr/local/tomcat/conf/guacamole.crt
        #- ./init/guacamole.key:/usr/local/tomcat/conf/guacamole.key
        #- ./init/server.xml:/usr/local/tomcat/conf/server.xml
      - ./init/cacerts:/usr/local/openjdk-8/jre/lib/security/cacerts
      - ./init/cacerts:/docker-java-home/jre/lib/security/cacerts
      - ./config/guacamole:/var/guacamole
    environment:
      GUACAMOLE_HOME: /var/guacamole
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOSTNAME: https://guac-keycloak.winllc-dev.com:8443/guacamole/#
      # https://keycloak.rfa.net:8443/auth/realms/master/.well-known/openid-configuration
      # https://guacamole.apache.org/doc/gug/openid-auth.html
      OPENID_AUTHORIZATION_ENDPOINT: https://guac-keycloak.winllc-dev.com:8443/auth/realms/Lab/protocol/openid-connect/auth
      OPENID_JWKS_ENDPOINT: https://guac-keycloak.winllc-dev.com:8443/auth/realms/Lab/protocol/openid-connect/certs
      OPENID_ISSUER: https://guac-keycloak.winllc-dev.com:8443/auth/realms/Lab
      OPENID_CLIENT_ID: guacamole
      OPENID_REDIRECT_URI: https://guac-keycloak.winllc-dev.com:8443/guacamole/#/settings/sessions
      OPENID_REDIRECT_URI: https://guac-keycloak.winllc-dev.com:8443/guacamole
      # OPENID_CLAIM_TYPE: sub
      # OPENID_CLAIM_TYPE: preferred_username
      OPENID_USERNAME_CLAIM_TYPE: email
      OPENID_GROUPS_CLAIM_TYPE: ad-groups
      OPENID_SCOPE: openid profile
      OPENID_ALLOWED_CLOCK_SKEW: 99999
      OPENID_MAX_TOKEN_VALIDITY: 300
      OPENID_MAX_NONCE_VALIDITY: 10
    depends_on:
      - postgres
      - guacd
      - keycloak
    
  nginx: 
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    volumes:
      - ./init/guacamole.crt:/etc/ssl/server.crt
      - ./init/guacamole.key:/etc/ssl/server.key
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf/:/etc/conf/
    ports:
      - 8443:8443
    depends_on:
      - guacamole
      - keycloak
    networks:
      - guac
  keycloakpostgres:
    image: docker.io/postgres:9.6
    restart: always
    volumes:
      - ./data/keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    networks:
      - guac
  keycloak:
    image: docker.io/jboss/keycloak:15.0.2
    restart: always
    depends_on:
      - keycloakpostgres
    environment:
      - DB_ADDR=keycloakpostgres
      - DB_DATABASE=keycloak
      - DB_PASSWORD=keycloak
      - DB_SCHEMA=public
      - DB_USER=keycloak
      - DB_VENDOR=POSTGRES
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_USER='admin'
      - PROXY_ADDRESS_FORWARDING=true
        #- KEYCLOAK_IMPORT="/tmp/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled"
        #- KEYCLOAK_MIGRATION_STRATEGY=OVERWRITE_EXISTING
    hostname: keycloak
    ports:
      - "8181:8080"
    tmpfs:
      - /run
      - /tmp
      - /opt/jboss/keycloak/standalone/tmp/vfs/temp
    volumes:
      - ./init/application.keystore:/opt/jboss/keycloak/standalone/configuration/application.keystore
      - ./init/application.keystore:/opt/jboss/keycloak/standalone/configuration/keystores/application.keystore
      - ./init/cacerts:/usr/lib/jvm/java-11-openjdk-11.0.6.10-0.el8_1.x86_64/lib/security/cacerts
      - ./init/cacerts:/usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.el8_4.x86_64/lib/security/cacerts
      - ./config/keycloak/guacamole-client.json:/opt/jboss/keycloak/standalone/configuration/guacamole-client.json
      - ./config/keycloak/realm-export.json:/tmp/realm-export.json
        #- ./config/keycloak/scripts:/opt/jboss/startup-scripts
      - ./extras/keycloak-otp-login/target/keycloak-otp-login.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-otp-login.jar
    networks:
      guac:
networks:
  guac:
    driver: bridge

